env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react', '@typescript-eslint']

settings:
  react:
    version: '16'
